## homo protein fata
homo_proteins: "homo.pro.fasta"

## groups of homologous 
groups: "groups.db"

## thread number of program
ncpus: 20

## evalue of tblastn
evalue: 1e-5

## num_alignments of tblastn
num_alignments: 20
