#!/bin/bash

## Convert hicpro to cool format use hicexplorer

matrix=$1
bedfile=$2
if [[ -z $bedfile || -z $matrix ]]; then
        echo
        echo "Usage: hicpro2cool rice_5000_iced.matrix rice_5000_abs.bed"
        echo
        return 1
fi

outname=`basename ${matrix%%.matrix}`
echo $outname
conda run -n hicexplorer hicConvertFormat -m $matrix --bedFileHicpro $bedfile --inputFormat hicpro --outputFormat cool -o $outname.cool

